name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa automaticamente todo dia à meia-noite
  workflow_dispatch:      # Permite rodar manualmente também

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Gerar a cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: gabrielrodrz
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      - name: Commit e push da animação
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Gerando Snake animation"
          add: "dist/*.svg dist/*.gif"
